app/admin/routes.py
from flask import Blueprint, render_template, session, redirect, url_for, request
from app import mysql
from datetime import datetime
from time import time
from PIL import Image
import MySQLdb.cursors ,os, io , re, base64, unicodedata





admin =  Blueprint('admin', __name__, url_prefix='/admin', template_folder='templates')



# login user 
@admin.route('/login', methods=['GET', 'POST'])
def admin_login():
    msg = ''
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form:
        username = request.form['username']
        password = request.form['password']
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM admin WHERE username = % s AND password = % s', (username, password, ))
        account = cursor.fetchone()
        if account: 
            session['loggedin'] = True
            session['id'] = account['admin_id']
            session['username'] = account['username']
            msg = 'Logged in successfully !'
            return  redirect(url_for('admin.admin_dashboard'))
        else:
            msg = 'Incorrect username / password !'
    return render_template('admin_login.html')


# log out user 
@admin.route('/logout')
def admin_logout():
    session.pop('loggedin', None)
    session.pop('admin_id', None)
    session.pop('username', None)
    return redirect(url_for('admin.admin_login'))

# register user 
@admin.route('/register', methods=['GET', 'POST'])
def admin_register():
    msg = ''
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form and 'email' in request.form :
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM admin WHERE username = % s', (username, ))
        account = cursor.fetchone()
        if account:
            msg = 'Account already exists !'
        elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
            msg = 'Invalid email address !'
        elif not re.match(r'[A-Za-z0-9]+', username):
            msg = 'Username must contain only characters and numbers !'
        elif not username or not password or not email:
            msg = 'Please fill out the form !'
        else:
            cursor.execute('INSERT INTO admin VALUES (NULL, % s, % s, % s, NULL)', (username,password, email,))
            mysql.connection.commit()
            msg = 'You have successfully registered !'
            return redirect(url_for('admin.admin_login'))
    elif request.method == 'POST':
        msg = 'Please fill out the form !'
    return render_template('admin_register.html')




@admin.route('/dashboard')
def admin_dashboard():
    return render_template('admin_dashboard.html')



@admin.route('/users')
def users():
    return render_template('users.html')


# getting posts 
@admin.route('/posts', methods=['POST','GET'])
def posts():
    if request.method == 'GET':
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM post')
        posts = cursor.fetchall()  # Fetch all rows from the result set
        cursor.close()
        return render_template('posts.html', posts=posts)
    return render_template('posts.html')



def slugify(title):
    #  remove assets from characters
    title = unicodedata.normalize('NFKD', title).encode('ASCII', 'ignore').decode('utf-8')

    # Replace non-alpha nummeric characters with hyphens
    title = re.sub(r'[^\w\s-]', '', title).strip().lower() 

    # Replace spaces with hyphens
    title = re.sub(r'[-\s]+', '-', title)

    return title

# adding posts 
@admin.route('/addposts', methods=['GET','POST'])
def addposts():
    if request.method == 'POST' and 'image' in request.files and 'title' in request.form and 'body':
        title = request.form['title']
        body = request.form['body']
        image_file = request.files['image']
        slug = slugify(title)
        created = datetime.now()


        if image_file:
            # Load the image using PIL
            image = Image.open(image_file)
            image_data = io.BytesIO()
            image.save(image_data, 'png')  #it can change to any image format
            image_data = image_data.getvalue()
        else:
            image_data = None

        
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('INSERT INTO post VALUES (NULL,% s, % s, % s, % s, % s)', (image_data, title, slug, body, created))
        mysql.connection.commit()
        msg = 'You have successfully added products !'

        return redirect(url_for('admin.posts'))
    
    return render_template('posts.html')


#updating posts
@admin.route("/update/<string:id>", methods=['GET','POST'])
def update_post(id):
    if request.method == 'POST':
        new_title = request.form['new_title']
        new_body = request.form['new_body']
        image_file = request.files['new_image']
        new_slug = slugify(new_title)
        new_created = datetime.now()

        if image_file:
            # Load the image using PIL
            image = Image.open(image_file)
            image_data = io.BytesIO()
            image.save(image_data, 'png')  #it can change to any image format
            image_data = image_data.getvalue()
        else:
            image_data = None


        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('UPDATE post SET image=%s,title=%s, slug = %s, body=%s, created=%s WHERE id = %s',(id,image_data, new_title, new_slug, new_body, new_created))

        mysql.connection.commit()
        cursor.close()

        return redirect(url_for('admin.posts'))
    
    cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute("SELECT * FROM post WHERE id = %s", (id,))
    car = cursor.fetchone()
    cursor.close()

    return render_template('posts.html')

        






#deleting posts posts
@admin.route("/delete/<string:id>", methods=['GET','POST', 'DELETE'])
def delete_post(id):

    cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute('DELETE FROM `post` WHERE id=%s', (id,))
    mysql.connection.commit()
    cursor.close()

    return redirect(url_for('admin.posts'))

app/admin/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock%}
    </title>

    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <!-- style css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='admin/style.css')}}">
    
    <!-- boxicon  jquery-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
   <!-- Your custom JavaScript -->


</head>
<body>

    

    {% block content %}




    {% endblock %}




    <!-- introduction  -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Popper.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <!-- js  -->
    <!-- js custom  -->
    <script src="{{ url_for('static', filename='users/js/main.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

    

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    
</body>

</html>

app/admin/templates/admin_login.html
{% extends 'admin_base.html' %}

         {% block title %}
         Register
         {% endblock%}
         
         {% block content %}
         <div class="container register ">
             <div class="login-register">
                  <!-- =======new tabs======== -->
                  <div class="tabs-wrapper">
                     <ul class="nav nav-pills chart-header-tab mb-3" id="pills-tab" role="tablist">
                         <li class="nav-item">
                             <a href="" class="nav-link chart-nav  " id="pill-month-tab" data-bs-toggle="pill" data-bs-target="#pill-month" type="button " role="tab" aria-controls="pill-month" aria-selected="false">REGISTER</a >
                         </li>
                         <li class="nav-item">
                             <a href="" class="nav-link chart-nav waves-light waves-effect " id="pills-year-tab" data-bs-toggle="pill" data-bs-target="#pills-year" type="button " role="tab" aria-controls="pills-year" aria-selected="false">LOGIN</a >
                         </li>
                     </ul>
                     <div class="tab-content" id="pills-tabContent">
                         <div class="tab-pane fade " id="pill-month" role="tabpanel" aria-labelledby="pill-month-tab" tabindex="0">
                             <div class="widget-content">
                                 <form method="POST" action="{{url_for('admin.admin_register')}}">
                                     <div class="form-group">
                                       <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
                                     </div>
                                     <div class="form-group">
                                       <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                                     </div>
                                     <div class="form-group">
                                       <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                                     </div>
                                     <div class="form-group">
                                       <input type="password" class="form-control" name="confirmpassword" id="exampleInputPassword1" placeholder="Confirm password">
                                     </div>
                                 
                                     <div class=" submit d-flex justify-content-center">
                                         <button type="submit" class="btn btn-primary form-group button-in">SIGN UP</button>
                                     </div>
                                     
                                     <div class="msg">
                                       {{ msg }}
                                     </div>
                                 </form>
                             </div>
                         </div>
                         <div class="tab-pane fade show active" id="pills-year" role="tabpanel" aria-labelledby="pills-year-tab" tabindex="0">
                             <div class="widget-content">
                                 <div id="yearly">
                                     <form method="POST" action="{{url_for('admin.admin_login')}}">
                                         <div class="form-group">
                                           <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
                                         </div>
                                         <!-- <div class="form-group">
                                           <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                                         </div> -->
                                         <div class="form-group">
                                           <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                                         </div>
                                         <div class="forgot">
                                           <a href="#" class="forgot-password">Forgot Password</a>
                                         </div>
                                         <div class=" submit d-flex justify-content-center">
                                             <button type="submit" class="btn btn-primary form-group button-in">SIGN IN</button>
                                         </div>
                                         
                                         <div class="msg">
                                           {{ msg }}
                                         </div>
                                     </form>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
                 
             
             </div>
         </div>
         
         
         
         {% endblock %}

app/admin/templates/admin_register.html
{% extends 'admin_base.html' %}

{% block title %}
Register
{% endblock%}

{% block content %}
<div class="container register ">
    <div class="login-register">
         <!-- =======new tabs======== -->
         <div class="tabs-wrapper">
            <ul class="nav nav-pills chart-header-tab mb-3" id="pills-tab" role="tablist">
                <li class="nav-item">
                    <a href="" class="nav-link chart-nav  " id="pill-month-tab" data-bs-toggle="pill" data-bs-target="#pill-month" type="button " role="tab" aria-controls="pill-month" aria-selected="false">REGISTER</a >
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link chart-nav waves-light waves-effect " id="pills-year-tab" data-bs-toggle="pill" data-bs-target="#pills-year" type="button " role="tab" aria-controls="pills-year" aria-selected="false">LOGIN</a >
                </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pill-month" role="tabpanel" aria-labelledby="pill-month-tab" tabindex="0">
                    <div class="widget-content">
                        <form method="POST" action="{{url_for('admin.admin_register')}}">
                            <div class="form-group">
                              <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
                            </div>
                            <div class="form-group">
                              <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                              <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                            </div>
                            <div class="form-group">
                              <input type="password" class="form-control" name="confirmpassword" id="exampleInputPassword1" placeholder="Confirm password">
                            </div>
                        
                            <div class=" submit d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary form-group button-in">SIGN UP</button>
                            </div>
                            
                            <div class="msg">
                              {{ msg }}
                            </div>
                        </form>
                    </div>
                </div>
                <div class="tab-pane fade" id="pills-year" role="tabpanel" aria-labelledby="pills-year-tab" tabindex="0">
                    <div class="widget-content">
                        <div id="yearly">
                            <form method="POST" action="{{url_for('admin.admin_login')}}">
                                <div class="form-group">
                                  <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
                                </div>
                                <!-- <div class="form-group">
                                  <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                                </div> -->
                                <div class="form-group">
                                  <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                                </div>
                                <div class="forgot">
                                  <a href="#" class="forgot-password">Forgot Password</a>
                                </div>
                                <div class=" submit d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary form-group button-in">SIGN IN</button>
                                </div>
                                
                                <div class="msg">
                                  {{ msg }}
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    </div>
</div>



{% endblock %}

app/admin/templates/posts.html
{% extends 'admin_dashboard_base.html' %}

{% block title %} 
Users
{% endblock %}


{% block content%}
<div class="container">
    <div class="row">
        <!-- Add posts... start -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
       Add Posts
    </button>
    
    
    {% for post in posts%}
      <!-- view posts... start -->
      <div class="card">
        <div class="img-card card">
            <img src="data:image/jpeg;base64,{{post.image|b64encode }}" alt="{{post.title}}">
          </div>
          <div class="card-body">
            <h5> {{post.title}} </h5>
          <p> {{ post.body | safe}} </p>
          </div>
          <div class="card-footer post-footer">
            {{post.created}}
            {{post.slug}}
          </div>
          <div class="options">
            <div class="update">
              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modalUpdate{{ post.id }}">
                Update Posts
             </button>
            </div>
            <div class="delete">
              <button type="button" class="btn btn-danger" data-toggle="modal" data-id = "{{post.id}}" data-target="#modalDelete{{ post.id }}">
                Delete Posts
             </button>
            </div>
          </div>
      </div>
       <!-- view posts... end -->
       {% endfor%}
      
      <!--  Add Posts Modal start-->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <form action="{{url_for('admin.addposts')}}" method="post" enctype="multipart/form-data">
                    <div class="">
                      <div class="mb-3">
                        <label for="formFile" class="form-label">Post Image</label>
                        <input class="form-control" type="file" name="image" id="formFile">
                      </div>
                     
                      <div class="form-group col-sm">
                        <label for="Carname">Title</label>
                        <input type="text" class="form-control" name="title" id="title" placeholder="Title">
                      </div>
                      
                      <div class="form-group col-sm">
                        <label for="description">Body</label>
                        <!-- create a textarea to be replaced by the ckeditor  -->
                      <textarea name="body" id="blogtext"></textarea>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                      </div>
                    </div>
                    
                </form>
            </div>
           
          </div>
        </div>
      </div>
      <!-- Add posts... end -->

      <!-- Update Posts modal start  -->
      {%for post in posts%}
      <div class="modal fade" id="modalUpdate{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <form action="/admin/update/{{post.id}}" method="post" enctype="multipart/form-data">
                    <div class="">
                      <div class="mb-3">
                        <label for="formFile" class="form-label">Post Image</label>
                        <input class="form-control" value = "{{post.image}} "type="file" name="new_image" id="formFile">
                      </div>
                     
                      <div class="form-group col-sm">
                        <label for="Carname">Title</label>
                        <input type="text" class="form-control" value="{{post.title}}" name="new_title" id="title" placeholder="Title">
                      </div>
                      
                      <div class="form-group col-sm">
                        <label for="description">Body</label>
                        <!-- create a textarea to be replaced by the ckeditor  -->
                      <textarea name="new_body" value="{{post.body | safe}}" id="blogtext"></textarea>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update</button>
                      </div>
                    </div>
                    
                </form>
            </div>
           
          </div>
        </div>
      </div>
      {%endfor%}

      <!-- Update Posts modal end  -->

      {%for post in posts%}
      <!-- Delete Posts modal start  -->
      <div class="modal fade" id="modalDelete{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete post</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <p> </p>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action="/admin/delete/{{post.id}}">
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
                </div>
            </div>
           
          </div>
        </div>
      </div>
      {%endfor%}
      
      <!-- Delete Posts modal end  -->

      
    </div>

</div>

                   
{% endblock %}

app/admin/templates/users.html
{% extends 'admin_dashboard_base.html' %}

{% block title %} 
Users
{% endblock %}


{% block content%}
<div class="container">
    <div class="row">
        <div class="show-user bg-white p-10">
            <div class="crud-uers">
                <h2 class="crud-user-head">Blog Users</h2>
                <hr class="horizontal-user">
                <div class="crud-user-body">
                     <!-- table for displaying fetched car } -->
      <table class="table car" style="border: 1px solid black;">
        <thead>
         <tr>
            <th scope="col">User Image</th>
             <th scope="col">User Name</th>
             <th scope="col">User Email</th>
             <th scope="col">Number Of Posts</th>
             <th scope="col">Options</th>
             
         </tr>
        </thead>
        <tbody>
         
         <tr>
             <td scope="col">
                <img src="{{url_for('static', filename='admin/assets/img/user-1.jpeg')}}" alt="" width="25px"  class="img-table">
             </td>
             <td scope="col">Vickie</td>
             <td scope="col"> vickie@gmail.com</td>
             <td scope="col">4 </td>
             
             <td>
              <button  class="btn btn-sm btn-warning pull-right" data-toggle="modal"  >Edit</button>
              <button  class="btn btn-sm btn-danger pull-right" data-toggle="modal">Delete</button>
             </td>
         </tr>
         
         
      </tbody>
     
     
    </table>
        
    
                </div>
                <div class="crud-user-footer">
    
                </div>
            </div>
        </div>
    
    </div>

</div>

                   
{% endblock %}